### ISSUE TITLE
Distant clouds rendering underwater before ocean ceiling renders causing visual issue

### ISSUE THREAD

**Issue by georgetarr** [alphaqu/extended-clouds#8]
![2022-08-19_10 44 44](https://user-images.githubusercontent.com/42141072/185592413-4bf35675-3e57-444e-89c7-1ca3996f0788.png)

When you first dive into water in minecraft, a fog effect occurs and slowly reduces (improving vision). At that starting point some far away clouds are bugged as seen above.

Though after a while it clears up as the water fog clears up.

![2022-08-19_10 45 20](https://user-images.githubusercontent.com/42141072/185592742-eaa12f5e-a272-4179-961f-edab5f64a6a6.png)

Issue may be caused in conjunction with FPS culling mods; list of installed mods:
![image](https://user-images.githubusercontent.com/42141072/185593126-6b5fead3-a8e4-4b15-8617-a67b8915048d.png)

**Comment by alphaqu** [comment]
Hi! This should be fixed in 1.2.2
